/* =====================================================================
   テロップデザイン定義
   - 1デザイン = 1 spec。variants は色違い（部分上書き）
   - pack でパック（商品）に紐づける。factory/calendar.json が参照する
   - フォントは全て Google Fonts (SIL OFL / Apache) のもののみ使用
   ===================================================================== */
(function (global) {
  'use strict';

  // Google Fonts 読み込み用（family: 必要ウェイト）
  // 各フォントの google/fonts リポジトリ内ファイル（factory/fetch_fonts.mjs がローカルキャッシュを作る）
  const FONTS = {
    'Noto Sans JP': { weights: ['700', '900'], files: [{ w: '100 900', p: 'ofl/notosansjp/NotoSansJP[wght].ttf' }] },
    'Dela Gothic One': { weights: ['400'], files: [{ w: '400', p: 'ofl/delagothicone/DelaGothicOne-Regular.ttf' }] },
    'M PLUS 1p': { weights: ['800', '900'], files: [{ w: '800', p: 'ofl/mplus1p/MPLUS1p-ExtraBold.ttf' }, { w: '900', p: 'ofl/mplus1p/MPLUS1p-Black.ttf' }] },
    'Zen Kaku Gothic New': { weights: ['700', '900'], files: [{ w: '700', p: 'ofl/zenkakugothicnew/ZenKakuGothicNew-Bold.ttf' }, { w: '900', p: 'ofl/zenkakugothicnew/ZenKakuGothicNew-Black.ttf' }] },
    'Zen Maru Gothic': { weights: ['700', '900'], files: [{ w: '700', p: 'ofl/zenmarugothic/ZenMaruGothic-Bold.ttf' }, { w: '900', p: 'ofl/zenmarugothic/ZenMaruGothic-Black.ttf' }] },
    'Zen Old Mincho': { weights: ['900'], files: [{ w: '900', p: 'ofl/zenoldmincho/ZenOldMincho-Black.ttf' }] },
    'Zen Antique Soft': { weights: ['400'], files: [{ w: '400', p: 'ofl/zenantiquesoft/ZenAntiqueSoft-Regular.ttf' }] },
    'Shippori Mincho B1': { weights: ['800'], files: [{ w: '800', p: 'ofl/shipporiminchob1/ShipporiMinchoB1-ExtraBold.ttf' }] },
    'Shippori Antique B1': { weights: ['400'], files: [{ w: '400', p: 'ofl/shipporiantiqueb1/ShipporiAntiqueB1-Regular.ttf' }] },
    'Kaisei Decol': { weights: ['700'], files: [{ w: '700', p: 'ofl/kaiseidecol/KaiseiDecol-Bold.ttf' }] },
    'RocknRoll One': { weights: ['400'], files: [{ w: '400', p: 'ofl/rocknrollone/RocknRollOne-Regular.ttf' }] },
    'Reggae One': { weights: ['400'], files: [{ w: '400', p: 'ofl/reggaeone/ReggaeOne-Regular.ttf' }] },
    'Rampart One': { weights: ['400'], files: [{ w: '400', p: 'ofl/rampartone/RampartOne-Regular.ttf' }] },
    'Mochiy Pop One': { weights: ['400'], files: [{ w: '400', p: 'ofl/mochiypopone/MochiyPopOne-Regular.ttf' }] },
    'Yusei Magic': { weights: ['400'], files: [{ w: '400', p: 'ofl/yuseimagic/YuseiMagic-Regular.ttf' }] },
    'DotGothic16': { weights: ['400'], files: [{ w: '400', p: 'ofl/dotgothic16/DotGothic16-Regular.ttf' }] },
    'Potta One': { weights: ['400'], files: [{ w: '400', p: 'ofl/pottaone/PottaOne-Regular.ttf' }] },
    'Train One': { weights: ['400'], files: [{ w: '400', p: 'ofl/trainone/TrainOne-Regular.ttf' }] },
    'Hachi Maru Pop': { weights: ['400'], files: [{ w: '400', p: 'ofl/hachimarupop/HachiMaruPop-Regular.ttf' }] },
    'Kiwi Maru': { weights: ['500'], files: [{ w: '500', p: 'ofl/kiwimaru/KiwiMaru-Medium.ttf' }] },
    'BIZ UDPGothic': { weights: ['700'], files: [{ w: '700', p: 'ofl/bizudpgothic/BIZUDPGothic-Bold.ttf' }] },
    'Yuji Syuku': { weights: ['400'], files: [{ w: '400', p: 'ofl/yujisyuku/YujiSyuku-Regular.ttf' }] },
    'Klee One': { weights: ['600'], files: [{ w: '600', p: 'ofl/kleeone/KleeOne-SemiBold.ttf' }] },
    'Stick': { weights: ['400'], files: [{ w: '400', p: 'ofl/stick/Stick-Regular.ttf' }] },
  };

  function googleFontsHref() {
    const fam = Object.entries(FONTS).map(([f, v]) => `family=${f.replace(/ /g, '+')}:wght@${v.weights.join(';')}`).join('&');
    return `https://fonts.googleapis.com/css2?${fam}&display=swap`;
  }

  const solid = (color) => ({ type: 'solid', color });
  const grad = (stops, angle) => ({ type: 'gradient', stops, angle: angle == null ? 90 : angle });
  const GOLD = grad([[0, '#fff6c2'], [0.35, '#f5d060'], [0.55, '#b8860b'], [0.75, '#f7dc6f'], [1, '#8a5a00']]);
  const SILVER = grad([[0, '#ffffff'], [0.4, '#d9dde3'], [0.6, '#8d95a1'], [0.8, '#e6e9ee'], [1, '#6c7480']]);
  const BRONZE = grad([[0, '#ffd9b3'], [0.45, '#c97b3a'], [0.65, '#7a3f12'], [1, '#e0a06a']]);

  const DESIGNS = [
    /* 1 */ {
      id: 'variety-tsukkomi', pack: 'tv-vol1', category: 'バラエティ', name: 'バラエティ・ツッコミ',
      sample: 'それ絶対ウソでしょ！',
      font: { family: 'Dela Gothic One', weight: 400, size: 104, letterSpacing: 0.01 },
      fill: grad([[0, '#fffbc4'], [0.45, '#ffd400'], [1, '#ff9a00']]),
      strokes: [{ width: 7, color: '#111111' }, { width: 16, color: '#ffffff' }],
      shadow: { dx: 7, dy: 7, blur: 0, color: 'rgba(0,0,0,0.55)' },
      anchor: { x: 'center', y: 'bottom', margin: 90 },
      variants: [
        { name: 'イエロー' },
        { name: 'ピンク', fill: grad([[0, '#ffe3f0'], [0.45, '#ff5fa8'], [1, '#e6007e']]) },
        { name: 'ブルー', fill: grad([[0, '#dff4ff'], [0.45, '#3fb6ff'], [1, '#0064d2']]) },
        { name: 'グリーン', fill: grad([[0, '#e9ffd9'], [0.45, '#7be04a'], [1, '#1d9a2e']]) },
      ],
    },
    /* 2 */ {
      id: 'variety-odoroki', pack: 'tv-vol1', category: 'バラエティ', name: 'バラエティ・驚き',
      sample: 'えっ、マジで！？',
      font: { family: 'Reggae One', weight: 400, size: 112, letterSpacing: 0.02 },
      fill: solid('#ffffff'),
      strokes: [{ width: 9, color: '#d7002b' }],
      extrude: { depth: 9, dx: 1, dy: 1, color: '#6d0016' },
      shadow: { dx: 4, dy: 8, blur: 10, color: 'rgba(0,0,0,0.45)' },
      variants: [
        { name: 'レッド' },
        { name: 'ブルー', strokes: [{ width: 9, color: '#0050c8' }], extrude: { depth: 9, dx: 1, dy: 1, color: '#062a6b' } },
        { name: 'パープル', strokes: [{ width: 9, color: '#7a1fbf' }], extrude: { depth: 9, dx: 1, dy: 1, color: '#3b0c63' } },
        { name: 'ブラック', strokes: [{ width: 9, color: '#111111' }], extrude: { depth: 9, dx: 1, dy: 1, color: '#555555' }, fill: solid('#ffe600') },
      ],
    },
    /* 3 */ {
      id: 'news-flash', pack: 'tv-vol1', category: 'ニュース', name: 'ニュース速報',
      sample: '〇〇市で震度4を観測 津波の心配なし',
      font: { family: 'Noto Sans JP', weight: 900, size: 66, letterSpacing: 0.02 },
      fill: solid('#ffffff'),
      box: { type: 'bar', fill: solid('#b7001e'), padY: 20, stroke: { width: 4, color: '#ffffff' } },
      tag: { text: '速報', font: { family: 'Noto Sans JP', weight: 900, size: 50 }, fill: solid('#b7001e'), box: { type: 'rect', fill: solid('#ffffff') }, padX: 20, padY: 6, gap: 28, keepOnPlate: true },
      anchor: { x: 'left', y: 'bottom', margin: 80 },
      portraitScale: 0.72,
      variants: [
        { name: 'レッド' },
        { name: 'ネイビー', box: { fill: solid('#0b2a5b') }, tag: { fill: solid('#0b2a5b') } },
        { name: 'ブラック', box: { fill: solid('#111111'), stroke: { width: 4, color: '#ffd400' } }, tag: { fill: solid('#111111'), box: { fill: solid('#ffd400') } } },
      ],
    },
    /* 4 */ {
      id: 'news-name', pack: 'tv-vol1', category: 'ニュース', name: 'ニュース・名前テロップ',
      sample: '山田 太郎', sampleSub: '株式会社サンプル 代表取締役',
      font: { family: 'Noto Sans JP', weight: 900, size: 64, letterSpacing: 0.06 },
      fill: solid('#111111'),
      box: { type: 'tagleft', fill: solid('#ffffff'), padX: 40, padY: 12, accent: { side: 'left', width: 18, color: '#0b2a5b' }, shadow: { dx: 0, dy: 6, blur: 14, color: 'rgba(0,0,0,0.35)' }, minWidth: 520 },
      sub: { position: 'above', align: 'left', indent: 0, gap: 0, font: { family: 'Noto Sans JP', weight: 700, size: 30, letterSpacing: 0.05 }, fill: solid('#ffffff'), box: { type: 'rect', fill: solid('#0b2a5b') }, lineHeight: 1.4 },
      anchor: { x: 'left', y: 'bottom', margin: 90 },
      variants: [
        { name: 'ネイビー' },
        { name: 'レッド', box: { accent: { color: '#c8102e' } }, sub: { box: { fill: solid('#c8102e') } } },
        { name: 'グリーン', box: { accent: { color: '#008a5e' } }, sub: { box: { fill: solid('#008a5e') } } },
        { name: 'ダーク', box: { fill: solid('#1b1b1b'), accent: { color: '#ffb400' } }, fill: solid('#ffffff'), sub: { box: { fill: solid('#ffb400') }, fill: solid('#1b1b1b') } },
      ],
    },
    /* 5 */ {
      id: 'wideshow', pack: 'tv-vol1', category: '情報番組', name: '情報番組・ワイドショー',
      sample: '今週末は全国的に晴れ 行楽日和に',
      font: { family: 'M PLUS 1p', weight: 900, size: 78, letterSpacing: 0.02 },
      fill: solid('#ffffff'),
      strokes: [{ width: 6, color: '#3a1d00' }],
      box: { type: 'skew', skew: 26, fill: grad([[0, '#ff8a00'], [1, '#ffc400']], 0), padX: 48, padY: 16, accent: { side: 'bottom', width: 10, color: '#ffffff' }, shadow: { dx: 0, dy: 8, blur: 16, color: 'rgba(0,0,0,0.35)' } },
      portraitScale: 0.7,
      variants: [
        { name: 'オレンジ' },
        { name: 'ブルー', box: { fill: grad([[0, '#0050c8'], [1, '#2ec4ff']], 0) }, strokes: [{ width: 6, color: '#001a4a' }] },
        { name: 'グリーン', box: { fill: grad([[0, '#0a8f3c'], [1, '#8ee000']], 0) }, strokes: [{ width: 6, color: '#0a3d15' }] },
        { name: 'ピンク', box: { fill: grad([[0, '#e6007e'], [1, '#ff8ac2']], 0) }, strokes: [{ width: 6, color: '#5a0033' }] },
      ],
    },
    /* 6 */ {
      id: 'documentary', pack: 'tv-vol1', category: 'ドキュメンタリー', name: 'ドキュメンタリー・明朝',
      sample: 'そして、彼は海へ向かった。',
      font: { family: 'Shippori Mincho B1', weight: 800, size: 74, letterSpacing: 0.1 },
      fill: solid('#ffffff'),
      shadow: { dx: 0, dy: 3, blur: 14, color: 'rgba(0,0,0,0.85)' },
      box: { type: 'underline', thickness: 3, fill: solid('rgba(255,255,255,0.85)'), padX: 20, padY: 18 },
      variants: [
        { name: 'ホワイト' },
        { name: 'ゴールド', fill: GOLD, box: { fill: solid('#d4b458') } },
        { name: 'ブラック', fill: solid('#111111'), shadow: { dx: 0, dy: 0, blur: 12, color: 'rgba(255,255,255,0.9)' }, box: { fill: solid('#111111') } },
      ],
    },
    /* 7 */ {
      id: 'quiz-gold', pack: 'tv-vol1', category: 'クイズ', name: 'クイズ・ゴールド',
      sample: '日本で一番高い山は？',
      font: { family: 'Kaisei Decol', weight: 700, size: 88, letterSpacing: 0.04 },
      fill: GOLD,
      strokes: [{ width: 5, color: '#3b2200' }],
      extrude: { depth: 8, dx: 1, dy: 1.2, color: '#4a2f00' },
      shadow: { dx: 0, dy: 10, blur: 14, color: 'rgba(0,0,0,0.5)' },
      box: { type: 'round', radius: 22, fill: grad([[0, '#0b1b3a'], [1, '#04101f']]), padX: 56, padY: 26, stroke: { width: 5, color: '#e6c25a' }, innerLine: { gap: 10, width: 2, color: 'rgba(230,194,90,0.8)' } },
      tag: { text: 'Q', position: 'left', font: { family: 'Kaisei Decol', weight: 700, size: 64 }, fill: GOLD, strokes: [{ width: 3, color: '#3b2200' }], box: { type: 'none' }, padX: 8, padY: 0, gap: 20 },
      portraitScale: 0.7,
      variants: [
        { name: 'ゴールド' },
        { name: 'シルバー', fill: SILVER, tag: { fill: SILVER }, box: { stroke: { color: '#cfd6df' }, innerLine: { color: 'rgba(207,214,223,0.8)' } } },
        { name: 'ブロンズ', fill: BRONZE, tag: { fill: BRONZE }, box: { stroke: { color: '#c97b3a' }, innerLine: { color: 'rgba(201,123,58,0.8)' } } },
      ],
    },
    /* 8 */ {
      id: 'travel', pack: 'tv-vol1', category: '旅', name: '旅番組・ゆる旅',
      sample: '絶景の露天風呂へ', sampleSub: '静岡・熱海',
      font: { family: 'Zen Maru Gothic', weight: 900, size: 84, letterSpacing: 0.04 },
      fill: solid('#5a3e2b'),
      box: { type: 'pill', fill: solid('#fff6e5'), padX: 60, padY: 14, stroke: { width: 5, color: '#e2b98a' }, shadow: { dx: 0, dy: 8, blur: 14, color: 'rgba(0,0,0,0.3)' } },
      sub: { position: 'above', align: 'left', indent: 40, gap: 6, font: { family: 'Zen Maru Gothic', weight: 900, size: 34 }, fill: solid('#ffffff'), box: { type: 'pill', fill: solid('#e0813a') }, lineHeight: 1.45 },
      variants: [
        { name: 'クリーム' },
        { name: 'ミント', box: { fill: solid('#eafff5'), stroke: { color: '#7fd8b0' } }, fill: solid('#1f5a44'), sub: { box: { fill: solid('#2aa57a') } } },
        { name: 'スカイ', box: { fill: solid('#eaf6ff'), stroke: { color: '#8ec9ff' } }, fill: solid('#1c4f80'), sub: { box: { fill: solid('#3d8ee0') } } },
        { name: 'ピーチ', box: { fill: solid('#fff0f3'), stroke: { color: '#ffb0c2' } }, fill: solid('#7a2b45'), sub: { box: { fill: solid('#ff6f91') } } },
      ],
    },
    /* 9 */ {
      id: 'gourmet-brush', pack: 'tv-vol1', category: 'グルメ', name: 'グルメ・筆文字',
      sample: '極上の一杯',
      font: { family: 'Yuji Syuku', weight: 400, size: 110, letterSpacing: 0.08 },
      fill: solid('#ffffff'),
      shadow: { dx: 3, dy: 3, blur: 4, color: 'rgba(0,0,0,0.5)' },
      box: { type: 'brush', jitter: 7, fill: solid('#b3121b'), padX: 54, padY: 10, shadow: { dx: 0, dy: 6, blur: 12, color: 'rgba(0,0,0,0.4)' } },
      variants: [
        { name: '朱' },
        { name: '墨', box: { fill: solid('#1b1b1b') }, fill: GOLD },
        { name: '藍', box: { fill: solid('#1c3f6e') } },
        { name: '白', box: { fill: solid('#f8f4ea') }, fill: solid('#1b1b1b'), shadow: null },
      ],
    },
    /* 10 */ {
      id: 'horror', pack: 'tv-vol1', category: 'ホラー', name: 'ホラー・心霊',
      sample: 'その夜、何かがいた',
      font: { family: 'Shippori Antique B1', weight: 400, size: 92, letterSpacing: 0.12 },
      fill: solid('#e9e4e4'),
      strokes: [{ width: 3, color: '#4a0000' }],
      glow: { color: 'rgba(200,0,0,0.9)', blur: 30, strength: 3 },
      shadow: { dx: 0, dy: 0, blur: 24, color: 'rgba(0,0,0,0.9)' },
      variants: [
        { name: '赤' },
        { name: '青白', glow: { color: 'rgba(80,160,255,0.9)', blur: 30, strength: 3 }, strokes: [{ width: 3, color: '#00224a' }] },
        { name: '緑', glow: { color: 'rgba(40,220,80,0.9)', blur: 30, strength: 3 }, strokes: [{ width: 3, color: '#003a10' }] },
      ],
    },
    /* 11 */ {
      id: 'sports', pack: 'tv-vol1', category: 'スポーツ', name: 'スポーツ・速報',
      sample: '逆転ゴール！', sampleSub: '後半 42分',
      font: { family: 'Noto Sans JP', weight: 900, size: 92, letterSpacing: 0.02, skew: 12 },
      fill: solid('#ffffff'),
      strokes: [{ width: 6, color: '#00205b' }],
      box: { type: 'skew', skew: 30, fill: grad([[0, '#0033a0'], [1, '#00a3ff']], 0), padX: 56, padY: 14, accent: { side: 'bottom', width: 12, color: '#ffe600' }, shadow: { dx: 0, dy: 8, blur: 14, color: 'rgba(0,0,0,0.4)' } },
      sub: { position: 'above', align: 'left', indent: 30, gap: 4, font: { family: 'Noto Sans JP', weight: 900, size: 34, skew: 12 }, fill: solid('#00205b'), box: { type: 'skew', skew: 12, fill: solid('#ffe600') }, lineHeight: 1.4 },
      variants: [
        { name: 'ブルー' },
        { name: 'レッド', box: { fill: grad([[0, '#a80000'], [1, '#ff5a36']], 0) }, strokes: [{ width: 6, color: '#4a0000' }], sub: { fill: solid('#4a0000') } },
        { name: 'グリーン', box: { fill: grad([[0, '#006d2c'], [1, '#5ad25a']], 0) }, strokes: [{ width: 6, color: '#003a15' }], sub: { fill: solid('#003a15') } },
        { name: 'ブラック', box: { fill: grad([[0, '#111111'], [1, '#444444']], 0) }, strokes: [{ width: 6, color: '#000000' }], sub: { fill: solid('#111111') } },
      ],
    },
    /* 12 */ {
      id: 'romance', pack: 'tv-vol1', category: '恋愛', name: '恋愛リアリティ',
      sample: '胸キュンが止まらない',
      font: { family: 'Yusei Magic', weight: 400, size: 96, letterSpacing: 0.03 },
      fill: solid('#ff4f8b'),
      strokes: [{ width: 10, color: '#ffffff' }],
      shadow: { dx: 0, dy: 6, blur: 14, color: 'rgba(255,80,140,0.45)' },
      deco: [{ type: 'sparkle', color: '#ffd6e6', size: 20, points: [[0.02, 0.1], [0.97, 0.15], [0.9, 0.95]] }],
      variants: [
        { name: 'ピンク' },
        { name: 'ラベンダー', fill: solid('#8a5cf6'), shadow: { dx: 0, dy: 6, blur: 14, color: 'rgba(138,92,246,0.45)' }, deco: [{ type: 'sparkle', color: '#e7dcff', size: 20, points: [[0.02, 0.1], [0.97, 0.15], [0.9, 0.95]] }] },
        { name: 'ミント', fill: solid('#1fb89a'), shadow: { dx: 0, dy: 6, blur: 14, color: 'rgba(31,184,154,0.45)' }, deco: [{ type: 'sparkle', color: '#d4fff4', size: 20, points: [[0.02, 0.1], [0.97, 0.15], [0.9, 0.95]] }] },
      ],
    },
    /* 13 */ {
      id: 'music-neon', pack: 'tv-vol1', category: '音楽', name: '音楽番組・ネオン',
      sample: '今夜、伝説になる',
      font: { family: 'Zen Kaku Gothic New', weight: 700, size: 92, letterSpacing: 0.1 },
      fill: solid('#ffffff'),
      strokes: [{ width: 3, color: '#ff2bd6' }],
      glow: { color: 'rgba(255,43,214,0.95)', blur: 36, strength: 3 },
      variants: [
        { name: 'ピンク' },
        { name: 'シアン', strokes: [{ width: 3, color: '#19e6ff' }], glow: { color: 'rgba(25,230,255,0.95)', blur: 36, strength: 3 } },
        { name: 'イエロー', strokes: [{ width: 3, color: '#ffe600' }], glow: { color: 'rgba(255,230,0,0.95)', blur: 36, strength: 3 } },
        { name: 'グリーン', strokes: [{ width: 3, color: '#39ff6a' }], glow: { color: 'rgba(57,255,106,0.95)', blur: 36, strength: 3 } },
      ],
    },
    /* 14 */ {
      id: 'kids-pop', pack: 'tv-vol1', category: '教育・キッズ', name: '教育・キッズポップ',
      sample: 'みんなでチャレンジ！',
      font: { family: 'Mochiy Pop One', weight: 400, size: 96, letterSpacing: 0.02 },
      fill: grad([[0, '#ff6b6b'], [0.33, '#ffb84d'], [0.66, '#5ccc7a'], [1, '#4d96ff']], 0),
      strokes: [{ width: 9, color: '#ffffff' }, { width: 15, color: '#3a3a3a' }],
      shadow: { dx: 5, dy: 6, blur: 0, color: 'rgba(0,0,0,0.35)' },
      variants: [
        { name: 'レインボー' },
        { name: 'オレンジ', fill: grad([[0, '#ffe08a'], [1, '#ff8a00']]) },
        { name: 'グリーン', fill: grad([[0, '#c8ff9a'], [1, '#2bb34a']]) },
        { name: 'ブルー', fill: grad([[0, '#bfe9ff'], [1, '#2a7bff']]) },
      ],
    },
    /* 15 */ {
      id: 'business', pack: 'tv-vol1', category: 'ビジネス・経済', name: 'ビジネス・経済',
      sample: '売上を2倍にする3つの施策', sampleSub: 'POINT 01',
      font: { family: 'Noto Sans JP', weight: 700, size: 62, letterSpacing: 0.04 },
      fill: solid('#ffffff'),
      box: { type: 'tagleft', skew: 26, fill: solid('#0b1f3a'), padX: 44, padY: 18, accent: { side: 'left', width: 16, color: '#ffb400' }, shadow: { dx: 0, dy: 6, blur: 14, color: 'rgba(0,0,0,0.35)' } },
      sub: { position: 'above', align: 'left', indent: 26, gap: 0, font: { family: 'Noto Sans JP', weight: 900, size: 28, letterSpacing: 0.18 }, fill: solid('#0b1f3a'), box: { type: 'rect', fill: solid('#ffb400') }, lineHeight: 1.4 },
      anchor: { x: 'left', y: 'bottom', margin: 90 },
      variants: [
        { name: 'ネイビー' },
        { name: 'ブラック', box: { fill: solid('#141414'), accent: { color: '#e60012' } }, sub: { fill: solid('#ffffff'), box: { fill: solid('#e60012') } } },
        { name: 'ホワイト', box: { fill: solid('#ffffff'), accent: { color: '#0b1f3a' } }, fill: solid('#0b1f3a'), sub: { fill: solid('#ffffff'), box: { fill: solid('#0b1f3a') } } },
      ],
    },
    /* 16 */ {
      id: 'retro-showa', pack: 'tv-vol1', category: 'レトロ', name: '昭和レトロ・版ずれ',
      sample: '懐かしの名曲特集',
      font: { family: 'Kaisei Decol', weight: 700, size: 96, letterSpacing: 0.06 },
      fill: solid('#f7ecd2'),
      strokes: [{ width: 7, color: '#2b2b2b' }],
      shadow: { dx: 9, dy: 9, blur: 0, color: '#d94f2b' },
      variants: [
        { name: 'クリーム×朱' },
        { name: 'ミント×紺', fill: solid('#bfeee0'), shadow: { dx: 9, dy: 9, blur: 0, color: '#1e3a6e' } },
        { name: 'レモン×茶', fill: solid('#fff1a8'), shadow: { dx: 9, dy: 9, blur: 0, color: '#6b4a2b' } },
      ],
    },
    /* 17 */ {
      id: 'drama-suspense', pack: 'tv-vol1', category: 'ドラマ', name: 'サスペンス・ドラマ帯',
      sample: '事件は、まだ終わっていない',
      font: { family: 'Zen Old Mincho', weight: 900, size: 66, letterSpacing: 0.14 },
      fill: solid('#ffffff'),
      align: 'center',
      box: { type: 'bar', fill: solid('rgba(0,0,0,0.78)'), padY: 26 },
      variants: [
        { name: 'ブラック' },
        { name: 'ホワイト', box: { fill: solid('rgba(255,255,255,0.9)') }, fill: solid('#111111') },
        { name: 'ワインレッド', box: { fill: solid('rgba(90,0,20,0.85)') } },
      ],
    },
    /* 18 */ {
      id: 'game-window', pack: 'tv-vol1', category: 'ゲーム', name: 'ゲーム実況・RPGウィンドウ',
      sample: 'ボスが あらわれた！',
      font: { family: 'DotGothic16', weight: 400, size: 88, letterSpacing: 0.06 },
      fill: solid('#ffffff'),
      box: { type: 'round', radius: 10, fill: solid('rgba(16,20,60,0.92)'), padX: 60, padY: 30, stroke: { width: 6, color: '#ffffff' }, innerLine: { gap: 10, width: 3, color: '#ffffff' } },
      variants: [
        { name: 'ホワイト' },
        { name: 'グリーン', fill: solid('#7cff6b') },
        { name: 'イエロー', fill: solid('#ffe94d') },
        { name: 'シアン', fill: solid('#5ff2ff') },
      ],
    },
    /* 19 */ {
      id: 'shopping', pack: 'tv-vol1', category: '通販', name: '通販・お得感',
      sample: 'なんと半額！',
      font: { family: 'RocknRoll One', weight: 400, size: 108, letterSpacing: 0.02 },
      fill: solid('#ffffff'),
      strokes: [{ width: 8, color: '#e60012' }, { width: 14, color: '#ffffff' }],
      shadow: { dx: 6, dy: 6, blur: 0, color: 'rgba(0,0,0,0.4)' },
      box: { type: 'skew', skew: 22, fill: solid('#ffd800'), padX: 70, padY: 12 },
      tag: { text: '今だけ', position: 'left', font: { family: 'RocknRoll One', weight: 400, size: 44 }, fill: solid('#ffffff'), box: { type: 'pill', fill: solid('#e60012') }, padX: 22, padY: 8, gap: 22 },
      variants: [
        { name: 'レッド×イエロー' },
        { name: 'ブルー×イエロー', strokes: [{ width: 8, color: '#0050c8' }, { width: 14, color: '#ffffff' }], tag: { box: { fill: solid('#0050c8') } } },
        { name: 'ピンク×ホワイト', strokes: [{ width: 8, color: '#e6007e' }, { width: 14, color: '#ffffff' }], box: { fill: solid('#ffffff') }, tag: { box: { fill: solid('#e6007e') } } },
      ],
    },
    /* 20 */ {
      id: 'weather', pack: 'tv-vol1', category: 'お天気', name: 'お天気コーナー',
      sample: 'あすは全国的に晴れ',
      font: { family: 'Kiwi Maru', weight: 500, size: 78, letterSpacing: 0.03 },
      fill: solid('#1b4b7a'),
      box: { type: 'round', radius: 30, fill: solid('#eaf7ff'), padX: 54, padY: 16, stroke: { width: 5, color: '#8ed0ff' }, shadow: { dx: 0, dy: 8, blur: 14, color: 'rgba(0,0,0,0.25)' } },
      tag: { text: '天気', position: 'left', font: { family: 'Kiwi Maru', weight: 500, size: 40 }, fill: solid('#ffffff'), box: { type: 'pill', fill: solid('#3d8ee0') }, padX: 22, padY: 8, gap: 22 },
      variants: [
        { name: 'スカイ' },
        { name: 'サンセット', box: { fill: solid('#fff3e6'), stroke: { color: '#ffb877' } }, fill: solid('#8a3c00'), tag: { box: { fill: solid('#ff8a3d') } } },
        { name: 'レイン', box: { fill: solid('#eef0ff'), stroke: { color: '#a9b1ff' } }, fill: solid('#2f3a8a'), tag: { box: { fill: solid('#5c6bff') } } },
      ],
    },
    /* 21 */ {
      id: 'vlog-natural', pack: 'tv-vol1', category: 'Vlog', name: 'Vlog・ナチュラル',
      sample: '今日は朝からカフェ巡り',
      font: { family: 'Zen Kaku Gothic New', weight: 700, size: 60, letterSpacing: 0.08 },
      fill: solid('#ffffff'),
      shadow: { dx: 0, dy: 2, blur: 12, color: 'rgba(0,0,0,0.6)' },
      deco: [{ type: 'sideBars', color: 'rgba(255,255,255,0.9)', thickness: 3, gap: 28 }],
      variants: [
        { name: 'ホワイト' },
        { name: 'ベージュ', fill: solid('#f3e5c9'), deco: [{ type: 'sideBars', color: 'rgba(243,229,201,0.9)', thickness: 3, gap: 28 }] },
        { name: 'ブラック', fill: solid('#1b1b1b'), shadow: { dx: 0, dy: 0, blur: 10, color: 'rgba(255,255,255,0.85)' }, deco: [{ type: 'sideBars', color: '#1b1b1b', thickness: 3, gap: 28 }] },
      ],
    },
    /* 22 */ {
      id: 'history-jidai', pack: 'tv-vol1', category: '歴史・時代劇', name: '歴史・時代劇',
      sample: '天下分け目の戦い',
      font: { family: 'Yuji Syuku', weight: 400, size: 104, letterSpacing: 0.1 },
      fill: GOLD,
      strokes: [{ width: 4, color: '#2a1a00' }],
      shadow: { dx: 4, dy: 4, blur: 6, color: 'rgba(0,0,0,0.6)' },
      box: { type: 'brush', jitter: 5, fill: solid('rgba(20,16,12,0.9)'), padX: 60, padY: 14 },
      deco: [{ type: 'lineTop', color: '#d4b458', thickness: 3, gap: 10 }, { type: 'lineBottom', color: '#d4b458', thickness: 3, gap: 10 }],
      variants: [
        { name: '金' },
        { name: '朱', fill: solid('#ffffff'), box: { fill: solid('rgba(150,20,20,0.92)') }, deco: [{ type: 'lineTop', color: '#ffffff', thickness: 3, gap: 10 }, { type: 'lineBottom', color: '#ffffff', thickness: 3, gap: 10 }] },
        { name: '白', fill: solid('#1b1b1b'), strokes: [], box: { fill: solid('rgba(248,244,234,0.95)') }, deco: [{ type: 'lineTop', color: '#1b1b1b', thickness: 3, gap: 10 }, { type: 'lineBottom', color: '#1b1b1b', thickness: 3, gap: 10 }] },
      ],
    },

    /* ===================== variety-vol1: バラエティ特化 ===================== */
    {
      id: 'v-tsukkomi-3', pack: 'variety-vol1', category: 'ツッコミ', name: 'ツッコミ・3重縁取り',
      sample: 'いや、それは違うだろ！',
      font: { family: 'Reggae One', weight: 400, size: 104, letterSpacing: 0.02 },
      fill: solid('#ffffff'),
      strokes: [{ width: 6, color: '#e60012' }, { width: 12, color: '#ffffff' }, { width: 17, color: '#1a1a1a' }],
      shadow: { dx: 6, dy: 6, blur: 0, color: 'rgba(0,0,0,0.5)' },
      variants: [
        { name: 'レッド' },
        { name: 'ブルー', strokes: [{ width: 6, color: '#0064d2' }, { width: 12, color: '#ffffff' }, { width: 17, color: '#1a1a1a' }] },
        { name: 'イエロー', fill: solid('#fff100'), strokes: [{ width: 6, color: '#1a1a1a' }, { width: 12, color: '#ffffff' }, { width: 17, color: '#e60012' }] },
        { name: 'グリーン', strokes: [{ width: 6, color: '#009944' }, { width: 12, color: '#ffffff' }, { width: 17, color: '#1a1a1a' }] },
      ],
    },
    {
      id: 'v-explosion', pack: 'variety-vol1', category: 'リアクション', name: '爆発吹き出し',
      sample: 'ドーン！',
      font: { family: 'Dela Gothic One', weight: 400, size: 120, letterSpacing: 0.02 },
      fill: grad([[0, '#ff3b3b'], [1, '#b80000']]),
      strokes: [{ width: 8, color: '#ffffff' }],
      shadow: { dx: 4, dy: 5, blur: 0, color: 'rgba(0,0,0,0.35)' },
      box: { type: 'burst', spikes: 20, spike: 44, fill: solid('#ffe600'), padX: 90, padY: 40, stroke: { width: 6, color: '#1a1a1a' }, shadow: { dx: 8, dy: 10, blur: 0, color: 'rgba(0,0,0,0.35)' } },
      anchor: { x: 'center', y: 'middle', margin: 90 },
      variants: [
        { name: 'イエロー×レッド' },
        { name: 'オレンジ×ホワイト', box: { fill: solid('#ff7a00') }, fill: solid('#ffffff'), strokes: [{ width: 8, color: '#8a2c00' }] },
        { name: 'ピンク×パープル', box: { fill: solid('#ff8ad0') }, fill: grad([[0, '#7a1fbf'], [1, '#3b0c63']]) },
        { name: 'ホワイト×ブラック', box: { fill: solid('#ffffff') }, fill: solid('#1a1a1a'), strokes: [{ width: 8, color: '#ffffff' }] },
      ],
    },
    {
      id: 'v-radial-shock', pack: 'variety-vol1', category: 'リアクション', name: '集中線・衝撃',
      sample: 'まさかの展開',
      font: { family: 'Rampart One', weight: 400, size: 128, letterSpacing: 0.04 },
      fill: solid('#ffffff'),
      strokes: [{ width: 4, color: '#1a1a1a' }],
      shadow: { dx: 6, dy: 6, blur: 0, color: 'rgba(0,0,0,0.4)' },
      deco: [{ type: 'radial', behind: true, color: 'rgba(20,20,20,0.9)', count: 48, width: 0.011, inner: 1.25 }],
      anchor: { x: 'center', y: 'middle', margin: 90 },
      portraitScale: 0.7,
      variants: [
        { name: 'ブラック' },
        { name: 'レッド', deco: [{ type: 'radial', behind: true, color: 'rgba(200,0,20,0.9)', count: 48, width: 0.011, inner: 1.25 }], strokes: [{ width: 4, color: '#8a0000' }] },
        { name: 'ブルー', deco: [{ type: 'radial', behind: true, color: 'rgba(0,60,180,0.9)', count: 48, width: 0.011, inner: 1.25 }], strokes: [{ width: 4, color: '#002a6e' }] },
        { name: 'ホワイト（暗い映像用）', deco: [{ type: 'radial', behind: true, color: 'rgba(255,255,255,0.9)', count: 48, width: 0.011, inner: 1.25 }], fill: solid('#ffe600') },
      ],
    },
    {
      id: 'v-zawazawa', pack: 'variety-vol1', category: 'ガヤ', name: 'ザワザワ・手書き',
      sample: 'ザワザワ…',
      font: { family: 'Yusei Magic', weight: 400, size: 96, letterSpacing: 0.22 },
      fill: solid('#3a3a3a'),
      strokes: [{ width: 9, color: '#ffffff' }],
      shadow: { dx: 5, dy: 5, blur: 0, color: 'rgba(0,0,0,0.25)' },
      variants: [
        { name: 'グレー' },
        { name: 'ブルーグレー', fill: solid('#2f4a6e') },
        { name: 'ブラウン', fill: solid('#5a3a1e') },
        { name: 'ホワイト', fill: solid('#ffffff'), strokes: [{ width: 9, color: '#3a3a3a' }] },
      ],
    },
    {
      id: 'v-gaya-small', pack: 'variety-vol1', category: 'ガヤ', name: 'ガヤ・小さめ傾き',
      sample: 'え、なんで？',
      font: { family: 'Mochiy Pop One', weight: 400, size: 68, letterSpacing: 0.02, skew: -8 },
      fill: solid('#ffffff'),
      strokes: [{ width: 6, color: '#1a1a1a' }],
      shadow: { dx: 3, dy: 3, blur: 0, color: 'rgba(0,0,0,0.4)' },
      anchor: { x: 'right', y: 'middle', margin: 120 },
      variants: [
        { name: 'ホワイト' },
        { name: 'イエロー', fill: solid('#ffe600') },
        { name: 'ピンク', fill: solid('#ff8ad0') },
        { name: 'ミント', fill: solid('#7cf5d0') },
      ],
    },
    {
      id: 'v-honnin', pack: 'variety-vol1', category: 'リアクション', name: 'ご本人登場',
      sample: 'ご本人登場',
      font: { family: 'M PLUS 1p', weight: 900, size: 92, letterSpacing: 0.04 },
      fill: solid('#ffffff'),
      strokes: [{ width: 5, color: '#5a0000' }],
      box: { type: 'skew', skew: 30, fill: grad([[0, '#c80000'], [1, '#ff4d4d']], 0), padX: 60, padY: 14, accent: { side: 'bottom', width: 10, color: '#ffe600' }, shadow: { dx: 0, dy: 8, blur: 14, color: 'rgba(0,0,0,0.4)' } },
      tag: { text: '本人', position: 'left', font: { family: 'M PLUS 1p', weight: 900, size: 44 }, fill: solid('#c80000'), box: { type: 'skew', skew: 12, fill: solid('#ffe600') }, padX: 20, padY: 6, gap: 24 },
      variants: [
        { name: 'レッド' },
        { name: 'ブルー', box: { fill: grad([[0, '#0033a0'], [1, '#2e8bff']], 0) }, strokes: [{ width: 5, color: '#001a4a' }], tag: { fill: solid('#0033a0') } },
        { name: 'ブラック', box: { fill: grad([[0, '#111111'], [1, '#4a4a4a']], 0) }, strokes: [{ width: 5, color: '#000000' }], tag: { fill: solid('#111111') } },
      ],
    },
    {
      id: 'v-staff-note', pack: 'variety-vol1', category: '注釈', name: 'スタッフ注釈',
      sample: '※スタッフが美味しくいただきました',
      font: { family: 'BIZ UDPGothic', weight: 700, size: 40, letterSpacing: 0.02 },
      fill: solid('#ffffff'),
      strokes: [{ width: 4, color: '#1a1a1a' }],
      anchor: { x: 'right', y: 'bottom', margin: 60 },
      variants: [
        { name: 'ホワイト' },
        { name: 'イエロー', fill: solid('#ffe600') },
        { name: 'ブラック（明るい映像用）', fill: solid('#1a1a1a'), strokes: [{ width: 4, color: '#ffffff' }] },
      ],
    },
    {
      id: 'v-kettei', pack: 'variety-vol1', category: '結果発表', name: '決定！ゴールド',
      sample: '優勝決定！',
      font: { family: 'Kaisei Decol', weight: 700, size: 104, letterSpacing: 0.05 },
      fill: GOLD,
      strokes: [{ width: 5, color: '#3b2200' }],
      extrude: { depth: 9, dx: 1, dy: 1.2, color: '#4a2f00' },
      shadow: { dx: 0, dy: 10, blur: 14, color: 'rgba(0,0,0,0.5)' },
      box: { type: 'ribbon', notch: 40, fill: grad([[0, '#c80000'], [1, '#7a0000']]), padX: 90, padY: 24, stroke: { width: 4, color: '#ffe27a' } },
      deco: [{ type: 'sparkle', color: '#fff6c2', size: 22, points: [[0.03, 0.12], [0.96, 0.18], [0.9, 0.9]] }],
      variants: [
        { name: 'レッド×ゴールド' },
        { name: 'ネイビー×ゴールド', box: { fill: grad([[0, '#0b1b3a'], [1, '#04101f']]) } },
        { name: 'ブラック×シルバー', box: { fill: grad([[0, '#2a2a2a'], [1, '#050505']]), stroke: { color: '#e6e9ee' } }, fill: SILVER },
      ],
    },
    {
      id: 'v-shocking-fact', pack: 'variety-vol1', category: 'ナレーション', name: '衝撃の事実・明朝',
      sample: '衝撃の事実',
      font: { family: 'Zen Old Mincho', weight: 900, size: 116, letterSpacing: 0.16 },
      fill: solid('#ffffff'),
      strokes: [{ width: 4, color: '#8a0000' }],
      glow: { color: 'rgba(200,0,0,0.85)', blur: 28, strength: 2 },
      shadow: { dx: 0, dy: 0, blur: 20, color: 'rgba(0,0,0,0.9)' },
      anchor: { x: 'center', y: 'middle', margin: 90 },
      variants: [
        { name: 'レッド' },
        { name: 'ブルー', strokes: [{ width: 4, color: '#002a6e' }], glow: { color: 'rgba(0,90,255,0.85)', blur: 28, strength: 2 } },
        { name: 'パープル', strokes: [{ width: 4, color: '#3b0c63' }], glow: { color: 'rgba(150,40,255,0.85)', blur: 28, strength: 2 } },
      ],
    },
    {
      id: 'v-ikari', pack: 'variety-vol1', category: 'リアクション', name: '怒り・ギザギザ',
      sample: '絶対に許さない',
      font: { family: 'Reggae One', weight: 400, size: 100, letterSpacing: 0.03 },
      fill: grad([[0, '#ff6a3d'], [0.5, '#e60012'], [1, '#8a0000']]),
      strokes: [{ width: 7, color: '#1a1a1a' }, { width: 13, color: '#ffffff' }],
      shadow: { dx: 6, dy: 6, blur: 0, color: 'rgba(0,0,0,0.45)' },
      deco: [{ type: 'zigzag', color: '#e60012', thickness: 6, amp: 10, step: 22, gap: 14 }],
      variants: [
        { name: 'レッド' },
        { name: 'パープル', fill: grad([[0, '#c56cff'], [0.5, '#7a1fbf'], [1, '#3b0c63']]), deco: [{ type: 'zigzag', color: '#7a1fbf', thickness: 6, amp: 10, step: 22, gap: 14 }] },
        { name: 'ブラック', fill: grad([[0, '#666666'], [0.5, '#222222'], [1, '#000000']]), deco: [{ type: 'zigzag', color: '#1a1a1a', thickness: 6, amp: 10, step: 22, gap: 14 }] },
      ],
    },
    {
      id: 'v-namida', pack: 'variety-vol1', category: 'ナレーション', name: '泣ける・涙',
      sample: '涙が止まらない',
      font: { family: 'Shippori Mincho B1', weight: 800, size: 92, letterSpacing: 0.12 },
      fill: solid('#eaf6ff'),
      strokes: [{ width: 3, color: '#1c4f80' }],
      glow: { color: 'rgba(120,190,255,0.8)', blur: 24, strength: 2 },
      shadow: { dx: 0, dy: 4, blur: 12, color: 'rgba(0,0,0,0.6)' },
      variants: [
        { name: 'ブルー' },
        { name: 'ラベンダー', strokes: [{ width: 3, color: '#4a2a7a' }], glow: { color: 'rgba(190,150,255,0.8)', blur: 24, strength: 2 } },
        { name: 'ホワイト', strokes: [{ width: 3, color: '#555555' }], glow: { color: 'rgba(255,255,255,0.8)', blur: 24, strength: 2 } },
      ],
    },
    {
      id: 'v-kansei', pack: 'variety-vol1', category: 'リアクション', name: '歓声・うおおお',
      sample: 'うおおおお！',
      font: { family: 'Dela Gothic One', weight: 400, size: 116, letterSpacing: 0.0 },
      fill: grad([[0, '#fffbc4'], [0.45, '#ffd400'], [1, '#ff7a00']]),
      strokes: [{ width: 7, color: '#1a1a1a' }, { width: 15, color: '#ffffff' }, { width: 20, color: '#e60012' }],
      shadow: { dx: 8, dy: 8, blur: 0, color: 'rgba(0,0,0,0.45)' },
      deco: [{ type: 'speedlines', color: '#ffffff', thickness: 8, n: 3, gap: 30, length: 110 }],
      anchor: { x: 'center', y: 'middle', margin: 90 },
      portraitScale: 0.65,
      variants: [
        { name: 'イエロー×レッド' },
        { name: 'ブルー×ネイビー', fill: grad([[0, '#dff4ff'], [0.45, '#3fb6ff'], [1, '#0064d2']]), strokes: [{ width: 7, color: '#001a4a' }, { width: 15, color: '#ffffff' }, { width: 20, color: '#0033a0' }] },
        { name: 'ピンク×パープル', fill: grad([[0, '#ffe3f0'], [0.45, '#ff5fa8'], [1, '#e6007e']]), strokes: [{ width: 7, color: '#3b0c63' }, { width: 15, color: '#ffffff' }, { width: 20, color: '#7a1fbf' }] },
      ],
    },
    {
      id: 'v-gaan', pack: 'variety-vol1', category: 'リアクション', name: 'ガーン・落胆',
      sample: 'ガーン…',
      font: { family: 'Klee One', weight: 600, size: 100, letterSpacing: 0.1, skew: 6 },
      fill: solid('#4a4a5a'),
      strokes: [{ width: 8, color: '#ffffff' }],
      shadow: { dx: 4, dy: 6, blur: 6, color: 'rgba(0,0,0,0.4)' },
      deco: [{ type: 'dropLines', color: '#ffffff', thickness: 7, n: 6, length: 70, gap: 16 }],
      anchor: { x: 'center', y: 'middle', margin: 90 },
      variants: [
        { name: 'グレー' },
        { name: 'ブルー', fill: solid('#2f4a8a'), deco: [{ type: 'dropLines', color: '#2f4a8a', thickness: 6, n: 6, length: 70, gap: 16 }] },
        { name: 'パープル', fill: solid('#4a2a7a'), deco: [{ type: 'dropLines', color: '#4a2a7a', thickness: 6, n: 6, length: 70, gap: 16 }] },
      ],
    },
    {
      id: 'v-kanpai', pack: 'variety-vol1', category: 'グルメ・飲み', name: '乾杯・ほろ酔い',
      sample: '今日は飲むぞ！',
      font: { family: 'Potta One', weight: 400, size: 92, letterSpacing: 0.03 },
      fill: solid('#ffffff'),
      strokes: [{ width: 7, color: '#c8501e' }],
      box: { type: 'pill', fill: solid('#5a3a1e'), padX: 70, padY: 14, stroke: { width: 5, color: '#ffb877' }, shadow: { dx: 0, dy: 8, blur: 14, color: 'rgba(0,0,0,0.4)' } },
      variants: [
        { name: 'ブラウン' },
        { name: 'ビール', box: { fill: solid('#f5b400'), stroke: { color: '#ffffff' } }, fill: solid('#5a3a1e'), strokes: [{ width: 7, color: '#ffffff' }] },
        { name: 'ワイン', box: { fill: solid('#6e0a2e'), stroke: { color: '#ffb0c2' } }, strokes: [{ width: 7, color: '#3a0018' }] },
        { name: 'ハイボール', box: { fill: solid('#c88a2e'), stroke: { color: '#fff1c8' } }, strokes: [{ width: 7, color: '#7a4a10' }] },
      ],
    },
    {
      id: 'v-question', pack: 'variety-vol1', category: 'リアクション', name: 'どういうこと？',
      sample: 'どういうこと？',
      font: { family: 'Mochiy Pop One', weight: 400, size: 100, letterSpacing: 0.02 },
      fill: solid('#7a1fbf'),
      strokes: [{ width: 9, color: '#ffffff' }, { width: 13, color: '#3b0c63' }],
      shadow: { dx: 5, dy: 6, blur: 0, color: 'rgba(0,0,0,0.35)' },
      deco: [{ type: 'bracket', color: '#ffffff', thickness: 8, size: 48 }],
      variants: [
        { name: 'パープル' },
        { name: 'ブルー', fill: solid('#0064d2'), strokes: [{ width: 9, color: '#ffffff' }, { width: 13, color: '#002a6e' }] },
        { name: 'グリーン', fill: solid('#1d9a2e'), strokes: [{ width: 9, color: '#ffffff' }, { width: 13, color: '#0a3d15' }] },
        { name: 'オレンジ', fill: solid('#ff7a00'), strokes: [{ width: 9, color: '#ffffff' }, { width: 13, color: '#8a2c00' }] },
      ],
    },
    {
      id: 'v-hanamaru', pack: 'variety-vol1', category: 'クイズ', name: '大正解・花マル',
      sample: '大正解！',
      font: { family: 'Yusei Magic', weight: 400, size: 112, letterSpacing: 0.06 },
      fill: solid('#e60012'),
      strokes: [{ width: 9, color: '#ffffff' }],
      shadow: { dx: 4, dy: 5, blur: 0, color: 'rgba(0,0,0,0.3)' },
      deco: [{ type: 'ring', color: '#e60012', thickness: 12, padX: 60, padY: 22 }],
      anchor: { x: 'center', y: 'middle', margin: 90 },
      variants: [
        { name: 'レッド' },
        { name: 'オレンジ', fill: solid('#ff7a00'), deco: [{ type: 'ring', color: '#ff7a00', thickness: 12, padX: 60, padY: 22 }] },
        { name: 'ピンク', fill: solid('#e6007e'), deco: [{ type: 'ring', color: '#e6007e', thickness: 12, padX: 60, padY: 22 }] },
      ],
    },
    {
      id: 'v-zannen', pack: 'variety-vol1', category: 'クイズ', name: '残念・不正解',
      sample: '残念…',
      font: { family: 'Zen Maru Gothic', weight: 900, size: 104, letterSpacing: 0.06 },
      fill: solid('#ffffff'),
      strokes: [{ width: 6, color: '#1c4f80' }],
      box: { type: 'round', radius: 26, fill: solid('#3d8ee0'), padX: 70, padY: 18, stroke: { width: 6, color: '#ffffff' }, shadow: { dx: 0, dy: 8, blur: 14, color: 'rgba(0,0,0,0.4)' } },
      anchor: { x: 'center', y: 'middle', margin: 90 },
      variants: [
        { name: 'ブルー' },
        { name: 'グレー', box: { fill: solid('#6b6b6b') }, strokes: [{ width: 6, color: '#3a3a3a' }] },
        { name: 'パープル', box: { fill: solid('#7a5cd6') }, strokes: [{ width: 6, color: '#3b2a7a' }] },
      ],
    },
    {
      id: 'v-taiketsu', pack: 'variety-vol1', category: '企画', name: '頂上決戦・対決',
      sample: '頂上決戦',
      font: { family: 'Noto Sans JP', weight: 900, size: 108, letterSpacing: 0.12, skew: 10 },
      fill: grad([[0, '#ffffff'], [0.6, '#dddddd'], [1, '#9a9a9a']]),
      strokes: [{ width: 5, color: '#000000' }],
      box: { type: 'skew', skew: 34, fill: grad([[0, '#000000'], [1, '#3a3a3a']], 0), padX: 80, padY: 18, accent: { side: 'bottom', width: 12, color: '#e60012' }, shadow: { dx: 0, dy: 10, blur: 16, color: 'rgba(0,0,0,0.5)' } },
      deco: [{ type: 'sideBars', color: '#e60012', thickness: 10, gap: 24 }],
      anchor: { x: 'center', y: 'middle', margin: 90 },
      variants: [
        { name: 'ブラック×レッド' },
        { name: 'ネイビー×イエロー', box: { fill: grad([[0, '#0b1b3a'], [1, '#1f3d7a']], 0), accent: { color: '#ffe600' } }, deco: [{ type: 'sideBars', color: '#ffe600', thickness: 10, gap: 24 }] },
        { name: 'レッド×ホワイト', box: { fill: grad([[0, '#8a0000'], [1, '#e60012']], 0), accent: { color: '#ffffff' } }, deco: [{ type: 'sideBars', color: '#ffffff', thickness: 10, gap: 24 }] },
      ],
    },
    {
      id: 'v-hisohiso', pack: 'variety-vol1', category: 'ガヤ', name: 'ヒソヒソ・内緒話',
      sample: '（ヒソヒソ）',
      font: { family: 'Klee One', weight: 600, size: 60, letterSpacing: 0.12 },
      fill: solid('#3a3a3a'),
      box: { type: 'speech', radius: 22, tail: 30, fill: solid('rgba(255,255,255,0.92)'), padX: 40, padY: 14, stroke: { width: 3, color: '#3a3a3a' } },
      anchor: { x: 'left', y: 'middle', margin: 120 },
      variants: [
        { name: 'ホワイト' },
        { name: 'クリーム', box: { fill: solid('rgba(255,246,229,0.95)') }, fill: solid('#5a3a1e') },
        { name: 'ブラック', box: { fill: solid('rgba(20,20,20,0.9)'), stroke: { color: '#ffffff' } }, fill: solid('#ffffff') },
      ],
    },
    {
      id: 'v-final-result', pack: 'variety-vol1', category: '結果発表', name: '最終結果発表',
      sample: '最終結果発表',
      font: { family: 'Dela Gothic One', weight: 400, size: 100, letterSpacing: 0.06 },
      fill: solid('#ffffff'),
      strokes: [{ width: 5, color: '#7a0000' }],
      box: { type: 'burst', spikes: 26, spike: 26, fill: grad([[0, '#ff3b3b'], [1, '#b80000']]), padX: 110, padY: 46, stroke: { width: 5, color: '#ffe27a' }, shadow: { dx: 0, dy: 10, blur: 16, color: 'rgba(0,0,0,0.45)' } },
      deco: [{ type: 'radial', behind: true, color: 'rgba(255,230,0,0.35)', count: 36, width: 0.02, inner: 1.35 }],
      anchor: { x: 'center', y: 'middle', margin: 90 },
      portraitScale: 0.7,
      variants: [
        { name: 'レッド×イエロー' },
        { name: 'ブルー×ホワイト', box: { fill: grad([[0, '#2e8bff'], [1, '#0033a0']]), stroke: { color: '#ffffff' } }, strokes: [{ width: 5, color: '#001a4a' }], deco: [{ type: 'radial', behind: true, color: 'rgba(255,255,255,0.35)', count: 36, width: 0.02, inner: 1.35 }] },
        { name: 'ブラック×ゴールド', box: { fill: grad([[0, '#3a3a3a'], [1, '#050505']]), stroke: { color: '#e6c25a' } }, fill: GOLD, strokes: [{ width: 5, color: '#3b2200' }], deco: [{ type: 'radial', behind: true, color: 'rgba(230,194,90,0.3)', count: 36, width: 0.02, inner: 1.35 }] },
      ],
    },
    /* ===================== news-vol1: ニュース・報道 ===================== */
    {
      id: 'n-flash-dark', pack: 'news-vol1', category: '速報', name: '速報・ダーク2段',
      sample: '政府 新たな経済対策を閣議決定',
      font: { family: 'Noto Sans JP', weight: 900, size: 62, letterSpacing: 0.02 },
      fill: solid('#ffffff'),
      box: { type: 'rect', fill: solid('rgba(10,10,10,0.84)'), padX: 40, padY: 18, minWidth: 900, accent: { side: 'left', width: 14, color: '#b7001e' } },
      tag: { position: 'above', text: '速報', font: { family: 'Noto Sans JP', weight: 900, size: 34, letterSpacing: 0.1 }, fill: solid('#ffffff'), box: { type: 'rect', fill: solid('#b7001e') }, padX: 22, padY: 4, gap: 0, keepOnPlate: true },
      anchor: { x: 'left', y: 'bottom', margin: 90 },
      variants: [
        { name: 'レッド' },
        { name: 'ネイビー', box: { accent: { color: '#0b2a5b' } }, tag: { box: { fill: solid('#0b2a5b') } } },
        { name: 'イエロー', box: { accent: { color: '#ffd400' } }, tag: { fill: solid('#111111'), box: { fill: solid('#ffd400') } } },
      ],
    },
    {
      id: 'n-lshape', pack: 'news-vol1', category: '帯', name: 'L字風・下帯',
      sample: '〇〇市 新庁舎が来春オープン 総工費120億円',
      font: { family: 'BIZ UDPGothic', weight: 700, size: 54, letterSpacing: 0.02 },
      fill: solid('#ffffff'),
      box: { type: 'bar', fill: solid('#0b2a5b'), padY: 22 },
      deco: [{ type: 'lineTop', full: true, color: '#ffffff', thickness: 3, gap: 0 }],
      tag: { text: 'NEWS', font: { family: 'Noto Sans JP', weight: 900, size: 36, letterSpacing: 0.08 }, fill: solid('#0b2a5b'), box: { type: 'rect', fill: solid('#ffffff') }, padX: 18, padY: 8, gap: 28, keepOnPlate: true },
      anchor: { x: 'left', y: 'bottom', margin: 70 },
      portraitScale: 0.72,
      variants: [
        { name: 'ネイビー' },
        { name: 'ブラック', box: { fill: solid('#111111') }, deco: [{ type: 'lineTop', full: true, color: '#b7001e', thickness: 4, gap: 0 }], tag: { fill: solid('#111111') } },
        { name: 'ホワイト', box: { fill: solid('rgba(255,255,255,0.96)') }, fill: solid('#0b2a5b'), deco: [{ type: 'lineTop', full: true, color: '#0b2a5b', thickness: 4, gap: 0 }], tag: { fill: solid('#ffffff'), box: { fill: solid('#0b2a5b') } } },
        { name: 'レッド', box: { fill: solid('#b7001e') }, tag: { fill: solid('#b7001e') } },
      ],
    },
    {
      id: 'n-name-dark', pack: 'news-vol1', category: '名前・肩書き', name: '名前・肩書き ダーク',
      sample: '山田 太郎', sampleSub: '〇〇大学 経済学部 教授',
      font: { family: 'Noto Sans JP', weight: 900, size: 60, letterSpacing: 0.08 },
      fill: solid('#ffffff'),
      box: { type: 'rect', fill: grad([[0, '#0b2a5b'], [1, '#123e82']], 0), padX: 44, padY: 14, minWidth: 560, accent: { side: 'bottom', width: 8, color: '#b7001e' }, shadow: { dx: 0, dy: 6, blur: 14, color: 'rgba(0,0,0,0.35)' } },
      sub: { position: 'below', align: 'left', indent: 0, gap: 6, font: { family: 'Noto Sans JP', weight: 700, size: 30, letterSpacing: 0.06 }, fill: solid('#ffffff'), box: { type: 'rect', fill: solid('rgba(0,0,0,0.75)') }, lineHeight: 1.35 },
      anchor: { x: 'left', y: 'bottom', margin: 90 },
      variants: [
        { name: 'ネイビー' },
        { name: 'ブラック', box: { fill: grad([[0, '#1a1a1a'], [1, '#3a3a3a']], 0), accent: { color: '#ffd400' } } },
        { name: 'レッド', box: { fill: grad([[0, '#7a0012'], [1, '#b7001e']], 0), accent: { color: '#ffffff' } } },
        { name: 'ホワイト', box: { fill: grad([[0, '#ffffff'], [1, '#e9edf3']], 0), accent: { color: '#0b2a5b' } }, fill: solid('#0b2a5b'), sub: { box: { fill: solid('#0b2a5b') } } },
      ],
    },
    {
      id: 'n-location', pack: 'news-vol1', category: '場所・日時', name: '場所テロップ',
      sample: '〇〇県〇〇市',
      font: { family: 'Zen Kaku Gothic New', weight: 900, size: 44, letterSpacing: 0.06 },
      fill: solid('#0b2a5b'),
      box: { type: 'tagleft', skew: 18, fill: solid('rgba(255,255,255,0.94)'), padX: 34, padY: 10, accent: { side: 'left', width: 12, color: '#b7001e' }, shadow: { dx: 0, dy: 4, blur: 10, color: 'rgba(0,0,0,0.35)' } },
      anchor: { x: 'left', y: 'top', margin: 70 },
      variants: [
        { name: 'ホワイト' },
        { name: 'ネイビー', box: { fill: solid('rgba(11,42,91,0.94)'), accent: { color: '#ffd400' } }, fill: solid('#ffffff') },
        { name: 'ブラック', box: { fill: solid('rgba(17,17,17,0.9)'), accent: { color: '#b7001e' } }, fill: solid('#ffffff') },
      ],
    },
    {
      id: 'n-live', pack: 'news-vol1', category: '中継', name: '中継・LIVE',
      sample: '〇〇市役所前から中継',
      font: { family: 'Noto Sans JP', weight: 700, size: 44, letterSpacing: 0.04 },
      fill: solid('#ffffff'),
      box: { type: 'rect', fill: solid('rgba(0,0,0,0.65)'), padX: 30, padY: 12 },
      tag: { text: 'LIVE', font: { family: 'Noto Sans JP', weight: 900, size: 36, letterSpacing: 0.1 }, fill: solid('#ffffff'), box: { type: 'rect', fill: solid('#b7001e') }, padX: 18, padY: 6, gap: 18, keepOnPlate: true },
      anchor: { x: 'right', y: 'top', margin: 70 },
      variants: [
        { name: 'レッド' },
        { name: 'ネイビー', tag: { box: { fill: solid('#0b2a5b') } } },
        { name: 'グリーン', tag: { box: { fill: solid('#008a5e') } } },
      ],
    },
    {
      id: 'n-weather-alert', pack: 'news-vol1', category: '気象', name: '気象警報・帯',
      sample: '〇〇地方に大雨警報 土砂災害に警戒',
      font: { family: 'Noto Sans JP', weight: 900, size: 56, letterSpacing: 0.02 },
      fill: solid('#111111'),
      box: { type: 'bar', fill: solid('#ffd400'), padY: 20, stroke: { width: 5, color: '#111111' } },
      tag: { text: '警報', font: { family: 'Noto Sans JP', weight: 900, size: 44, letterSpacing: 0.06 }, fill: solid('#ffd400'), box: { type: 'rect', fill: solid('#111111') }, padX: 20, padY: 6, gap: 26, keepOnPlate: true },
      anchor: { x: 'left', y: 'bottom', margin: 80 },
      portraitScale: 0.72,
      variants: [
        { name: 'イエロー' },
        { name: 'レッド', box: { fill: solid('#b7001e'), stroke: { color: '#ffffff' } }, fill: solid('#ffffff'), tag: { fill: solid('#b7001e'), box: { fill: solid('#ffffff') } } },
        { name: 'パープル', box: { fill: solid('#5b1a8a'), stroke: { color: '#ffffff' } }, fill: solid('#ffffff'), tag: { fill: solid('#5b1a8a'), box: { fill: solid('#ffffff') } } },
      ],
    },
    {
      id: 'n-election', pack: 'news-vol1', category: '選挙', name: '選挙速報・当確',
      sample: '山田 太郎', sampleSub: '〇〇党・新　当選確実',
      font: { family: 'Noto Sans JP', weight: 900, size: 66, letterSpacing: 0.08 },
      fill: solid('#ffffff'),
      box: { type: 'rect', fill: solid('#0b2a5b'), padX: 40, padY: 14, minWidth: 620, shadow: { dx: 0, dy: 6, blur: 14, color: 'rgba(0,0,0,0.35)' } },
      tag: { text: '当確', font: { family: 'Noto Sans JP', weight: 900, size: 48, letterSpacing: 0.06 }, fill: solid('#ffffff'), box: { type: 'rect', fill: solid('#b7001e') }, padX: 18, padY: 6, gap: 22, keepOnPlate: true },
      sub: { position: 'below', align: 'left', indent: 0, gap: 8, font: { family: 'Noto Sans JP', weight: 700, size: 30, letterSpacing: 0.06 }, fill: solid('#0b2a5b'), box: { type: 'rect', fill: solid('#ffffff') }, lineHeight: 1.3 },
      anchor: { x: 'left', y: 'bottom', margin: 90 },
      variants: [
        { name: 'ネイビー×レッド' },
        { name: 'ブラック×イエロー', box: { fill: solid('#111111') }, tag: { fill: solid('#111111'), box: { fill: solid('#ffd400') } }, sub: { fill: solid('#111111'), box: { fill: solid('#ffd400') } } },
        { name: 'ホワイト×レッド', box: { fill: solid('#ffffff') }, fill: solid('#0b2a5b'), sub: { fill: solid('#ffffff'), box: { fill: solid('#0b2a5b') } } },
      ],
    },
    {
      id: 'n-market', pack: 'news-vol1', category: '経済・マーケット', name: '株価・為替ボード',
      sample: '日経平均 39,850.12', sampleSub: '前日比 +312.45（+0.79%）',
      font: { family: 'Noto Sans JP', weight: 900, size: 58, letterSpacing: 0.02 },
      fill: solid('#ffffff'),
      box: { type: 'rect', fill: solid('#0a1628'), padX: 36, padY: 14, accent: { side: 'left', width: 14, color: '#00c46a' }, stroke: { width: 2, color: 'rgba(255,255,255,0.25)' } },
      sub: { position: 'right', gap: 18, font: { family: 'Noto Sans JP', weight: 900, size: 40, letterSpacing: 0.02 }, fill: solid('#00c46a'), box: { type: 'rect', fill: solid('#0a1628'), stroke: { width: 2, color: 'rgba(255,255,255,0.25)' } }, lineHeight: 1.2 },
      anchor: { x: 'left', y: 'bottom', margin: 90 },
      variants: [
        { name: '上昇グリーン' },
        { name: '下落レッド', box: { accent: { color: '#ff4d4d' } }, sub: { fill: solid('#ff4d4d') } },
        { name: 'ブルー', box: { accent: { color: '#3aa0ff' } }, sub: { fill: solid('#3aa0ff') } },
        { name: 'ゴールド', box: { accent: { color: '#e6c25a' } }, sub: { fill: solid('#e6c25a') } },
      ],
    },
    {
      id: 'n-caution', pack: 'news-vol1', category: '注意喚起', name: '注意喚起・黄黒',
      sample: '不審な電話にご注意ください',
      font: { family: 'Noto Sans JP', weight: 900, size: 56, letterSpacing: 0.04 },
      fill: solid('#111111'),
      box: { type: 'rect', fill: solid('#ffd400'), padX: 44, padY: 16, stroke: { width: 8, color: '#111111' }, innerLine: { gap: 12, width: 3, color: '#111111' } },
      tag: { text: '注意', font: { family: 'Noto Sans JP', weight: 900, size: 44, letterSpacing: 0.06 }, fill: solid('#ffd400'), box: { type: 'rect', fill: solid('#111111') }, padX: 18, padY: 8, gap: 24, keepOnPlate: true },
      anchor: { x: 'center', y: 'bottom', margin: 90 },
      variants: [
        { name: 'イエロー' },
        { name: 'オレンジ', box: { fill: solid('#ff8a00') }, tag: { fill: solid('#ff8a00') } },
        { name: 'レッド', box: { fill: solid('#b7001e'), stroke: { color: '#ffffff' }, innerLine: { color: '#ffffff' } }, fill: solid('#ffffff'), tag: { fill: solid('#b7001e'), box: { fill: solid('#ffffff') } } },
      ],
    },
    {
      id: 'n-sponsor', pack: 'news-vol1', category: '提供・協力', name: '提供テロップ',
      sample: '株式会社サンプル', sampleSub: '提供',
      font: { family: 'Noto Sans JP', weight: 700, size: 52, letterSpacing: 0.1 },
      fill: solid('#ffffff'),
      shadow: { dx: 0, dy: 2, blur: 10, color: 'rgba(0,0,0,0.75)' },
      sub: { position: 'above', align: 'center', gap: 6, font: { family: 'Noto Sans JP', weight: 700, size: 30, letterSpacing: 0.2 }, fill: solid('#ffffff'), shadow: { dx: 0, dy: 2, blur: 8, color: 'rgba(0,0,0,0.75)' }, lineHeight: 1.2 },
      anchor: { x: 'center', y: 'bottom', margin: 110 },
      variants: [
        { name: 'ホワイト' },
        { name: 'ゴールド', fill: GOLD, strokes: [{ width: 2, color: '#3b2200' }], sub: { fill: solid('#f5d060') } },
        { name: 'ブラック', fill: solid('#111111'), strokes: [{ width: 3, color: '#ffffff' }], shadow: null, sub: { fill: solid('#111111'), strokes: [{ width: 2, color: '#ffffff' }], shadow: null } },
      ],
    },
    {
      id: 'n-cooperation', pack: 'news-vol1', category: '提供・協力', name: '取材協力',
      sample: '〇〇市観光協会',
      font: { family: 'Noto Sans JP', weight: 700, size: 36, letterSpacing: 0.06 },
      fill: solid('#111111'),
      box: { type: 'rect', fill: solid('rgba(255,255,255,0.92)'), padX: 26, padY: 8 },
      tag: { text: '取材協力', font: { family: 'Noto Sans JP', weight: 900, size: 26, letterSpacing: 0.1 }, fill: solid('#ffffff'), box: { type: 'rect', fill: solid('#0b2a5b') }, padX: 14, padY: 8, gap: 14, keepOnPlate: true },
      anchor: { x: 'right', y: 'bottom', margin: 70 },
      variants: [
        { name: 'ネイビー' },
        { name: 'レッド', tag: { box: { fill: solid('#b7001e') } } },
        { name: 'ブラック', box: { fill: solid('rgba(17,17,17,0.86)') }, fill: solid('#ffffff'), tag: { fill: solid('#111111'), box: { fill: solid('#ffd400') } } },
      ],
    },
    {
      id: 'n-note', pack: 'news-vol1', category: '注釈', name: '再現VTR・注釈',
      sample: '※映像はイメージです',
      font: { family: 'Zen Kaku Gothic New', weight: 700, size: 36, letterSpacing: 0.06 },
      fill: solid('#ffffff'),
      box: { type: 'rect', fill: solid('rgba(0,0,0,0.55)'), padX: 20, padY: 6 },
      anchor: { x: 'left', y: 'top', margin: 70 },
      variants: [
        { name: 'ブラック' },
        { name: 'ホワイト', box: { fill: solid('rgba(255,255,255,0.9)') }, fill: solid('#111111') },
        { name: 'レッド枠', box: { fill: solid('rgba(0,0,0,0.55)'), stroke: { width: 2, color: '#ff4d4d' } } },
      ],
    },
    {
      id: 'n-expert', pack: 'news-vol1', category: 'コメント', name: '専門家コメント',
      sample: '「今後さらに拡大する可能性がある」', sampleSub: '〇〇研究所 山田 太郎 所長',
      font: { family: 'Noto Sans JP', weight: 700, size: 50, letterSpacing: 0.02 },
      fill: solid('#111111'),
      box: { type: 'round', radius: 10, fill: solid('rgba(255,255,255,0.95)'), padX: 40, padY: 16, accent: { side: 'left', width: 12, color: '#0b2a5b' }, shadow: { dx: 0, dy: 6, blur: 14, color: 'rgba(0,0,0,0.35)' } },
      sub: { position: 'below', align: 'left', indent: 0, gap: 8, font: { family: 'Noto Sans JP', weight: 700, size: 28, letterSpacing: 0.05 }, fill: solid('#ffffff'), box: { type: 'rect', fill: solid('#0b2a5b') }, lineHeight: 1.3 },
      anchor: { x: 'left', y: 'bottom', margin: 90 },
      variants: [
        { name: 'ネイビー' },
        { name: 'レッド', box: { accent: { color: '#b7001e' } }, sub: { box: { fill: solid('#b7001e') } } },
        { name: 'グリーン', box: { accent: { color: '#008a5e' } }, sub: { box: { fill: solid('#008a5e') } } },
        { name: 'ダーク', box: { fill: solid('rgba(20,20,20,0.9)'), accent: { color: '#ffd400' } }, fill: solid('#ffffff'), sub: { fill: solid('#111111'), box: { fill: solid('#ffd400') } } },
      ],
    },
    {
      id: 'n-viewer', pack: 'news-vol1', category: 'コメント', name: '視聴者の声',
      sample: '「うちの近所でも見かけました」',
      font: { family: 'Zen Maru Gothic', weight: 700, size: 48, letterSpacing: 0.02 },
      fill: solid('#333333'),
      box: { type: 'speech', radius: 20, tail: 26, fill: solid('rgba(255,255,255,0.95)'), padX: 36, padY: 14, stroke: { width: 3, color: '#0b2a5b' } },
      tag: { text: '視聴者', font: { family: 'Zen Maru Gothic', weight: 900, size: 28, letterSpacing: 0.04 }, fill: solid('#ffffff'), box: { type: 'pill', fill: solid('#0b2a5b') }, padX: 16, padY: 6, gap: 16, keepOnPlate: true },
      anchor: { x: 'left', y: 'middle', margin: 110 },
      variants: [
        { name: 'ネイビー' },
        { name: 'レッド', box: { stroke: { color: '#b7001e' } }, tag: { box: { fill: solid('#b7001e') } } },
        { name: 'グリーン', box: { stroke: { color: '#008a5e' } }, tag: { box: { fill: solid('#008a5e') } } },
      ],
    },
    {
      id: 'n-followup', pack: 'news-vol1', category: '速報', name: '続報・帯',
      sample: '〇〇市の断水 きょう夕方までに復旧の見通し',
      font: { family: 'Noto Sans JP', weight: 900, size: 56, letterSpacing: 0.02 },
      fill: solid('#ffffff'),
      box: { type: 'bar', fill: solid('#111111'), padY: 20, stroke: { width: 3, color: '#e8730c' } },
      tag: { text: '続報', font: { family: 'Noto Sans JP', weight: 900, size: 46, letterSpacing: 0.06 }, fill: solid('#ffffff'), box: { type: 'rect', fill: solid('#e8730c') }, padX: 20, padY: 6, gap: 26, keepOnPlate: true },
      anchor: { x: 'left', y: 'bottom', margin: 80 },
      portraitScale: 0.72,
      variants: [
        { name: 'オレンジ' },
        { name: 'ブルー', box: { stroke: { color: '#2e8bff' } }, tag: { box: { fill: solid('#2e8bff') } } },
        { name: 'グリーン', box: { stroke: { color: '#00a86b' } }, tag: { box: { fill: solid('#00a86b') } } },
      ],
    },
    {
      id: 'n-exclusive', pack: 'news-vol1', category: '独自', name: '独自取材',
      sample: '関係者が初めて証言',
      font: { family: 'Noto Sans JP', weight: 900, size: 62, letterSpacing: 0.04 },
      fill: solid('#ffffff'),
      box: { type: 'rect', fill: solid('rgba(0,0,0,0.85)'), padX: 40, padY: 16, minWidth: 800, accent: { side: 'bottom', width: 6, color: '#e6c25a' } },
      tag: { text: '独自', font: { family: 'Noto Sans JP', weight: 900, size: 48, letterSpacing: 0.06 }, fill: solid('#111111'), box: { type: 'rect', fill: GOLD }, padX: 20, padY: 6, gap: 24, keepOnPlate: true },
      anchor: { x: 'left', y: 'bottom', margin: 90 },
      variants: [
        { name: 'ゴールド' },
        { name: 'レッド', box: { accent: { color: '#b7001e' } }, tag: { fill: solid('#ffffff'), box: { fill: solid('#b7001e') } } },
        { name: 'ホワイト', box: { accent: { color: '#ffffff' } }, tag: { fill: solid('#111111'), box: { fill: solid('#ffffff') } } },
      ],
    },
    {
      id: 'n-subtitle', pack: 'news-vol1', category: '字幕', name: '字幕・2行黒帯',
      sample: '取材に対し「事実関係を確認中」と\n文書で回答した',
      font: { family: 'BIZ UDPGothic', weight: 700, size: 46, letterSpacing: 0.02 },
      lineHeight: 1.4,
      fill: solid('#ffffff'),
      box: { type: 'rect', fill: solid('rgba(0,0,0,0.6)'), padX: 40, padY: 16 },
      align: 'center',
      anchor: { x: 'center', y: 'bottom', margin: 80 },
      variants: [
        { name: 'ブラック' },
        { name: 'ホワイト', box: { fill: solid('rgba(255,255,255,0.88)') }, fill: solid('#111111') },
        { name: 'ネイビー', box: { fill: solid('rgba(11,42,91,0.85)') } },
        { name: 'イエロー字', fill: solid('#ffe97a') },
      ],
    },
    {
      id: 'n-headline', pack: 'news-vol1', category: '見出し', name: 'トップニュース見出し',
      sample: '物価高対策 きょう決定',
      font: { family: 'Noto Sans JP', weight: 900, size: 76, letterSpacing: 0.04 },
      fill: solid('#ffffff'),
      box: { type: 'rect', fill: grad([[0, '#0b2a5b'], [1, '#1a4d9e']], 0), padX: 48, padY: 18, accent: { side: 'bottom', width: 10, color: '#b7001e' }, shadow: { dx: 0, dy: 8, blur: 16, color: 'rgba(0,0,0,0.4)' } },
      tag: { position: 'above', text: 'TOP NEWS', font: { family: 'Noto Sans JP', weight: 900, size: 30, letterSpacing: 0.16 }, fill: solid('#ffffff'), box: { type: 'rect', fill: solid('#b7001e') }, padX: 20, padY: 6, gap: 0, keepOnPlate: true },
      anchor: { x: 'left', y: 'bottom', margin: 90 },
      variants: [
        { name: 'ネイビー' },
        { name: 'ブラック', box: { fill: grad([[0, '#111111'], [1, '#3a3a3a']], 0), accent: { color: '#ffd400' } }, tag: { fill: solid('#111111'), box: { fill: solid('#ffd400') } } },
        { name: 'レッド', box: { fill: grad([[0, '#8a0012'], [1, '#c8102e']], 0), accent: { color: '#ffffff' } }, tag: { fill: solid('#b7001e'), box: { fill: solid('#ffffff') } } },
        { name: 'ホワイト', box: { fill: grad([[0, '#ffffff'], [1, '#e6e9ee']], 0), accent: { color: '#0b2a5b' } }, fill: solid('#0b2a5b'), tag: { box: { fill: solid('#0b2a5b') } } },
      ],
    },
    {
      id: 'n-stat', pack: 'news-vol1', category: '統計・数字', name: '数字・統計',
      sample: '3,281人', sampleSub: '前の週から +12.4%',
      font: { family: 'Noto Sans JP', weight: 900, size: 120, letterSpacing: 0 },
      fill: solid('#ffffff'),
      strokes: [{ width: 4, color: '#0b2a5b' }],
      shadow: { dx: 0, dy: 6, blur: 14, color: 'rgba(0,0,0,0.5)' },
      sub: { position: 'below', align: 'center', gap: 4, font: { family: 'Noto Sans JP', weight: 700, size: 36, letterSpacing: 0.04 }, fill: solid('#ffffff'), box: { type: 'rect', fill: solid('#b7001e') }, lineHeight: 1.3 },
      anchor: { x: 'center', y: 'middle', margin: 90 },
      variants: [
        { name: 'ネイビー' },
        { name: 'レッド', strokes: [{ width: 4, color: '#b7001e' }], sub: { box: { fill: solid('#0b2a5b') } } },
        { name: 'ブラック', strokes: [{ width: 4, color: '#111111' }], sub: { box: { fill: solid('#111111') } } },
        { name: 'イエロー', fill: solid('#ffe600'), strokes: [{ width: 4, color: '#111111' }], sub: { fill: solid('#111111'), box: { fill: solid('#ffe600') } } },
      ],
    },
    {
      id: 'n-datetime', pack: 'news-vol1', category: '場所・日時', name: '日時スタンプ',
      sample: '9月16日（水）午前8時ごろ',
      font: { family: 'BIZ UDPGothic', weight: 700, size: 38, letterSpacing: 0.06 },
      fill: solid('#ffffff'),
      box: { type: 'round', radius: 6, fill: solid('rgba(0,0,0,0.65)'), padX: 24, padY: 8, stroke: { width: 2, color: 'rgba(255,255,255,0.7)' } },
      anchor: { x: 'right', y: 'top', margin: 70 },
      variants: [
        { name: 'ブラック' },
        { name: 'ホワイト', box: { fill: solid('rgba(255,255,255,0.92)'), stroke: { color: '#0b2a5b' } }, fill: solid('#0b2a5b') },
        { name: 'ネイビー', box: { fill: solid('rgba(11,42,91,0.9)'), stroke: { color: 'rgba(255,255,255,0.7)' } } },
      ],
    },
  ];

  const PACKS = {
    'tv-vol1': { name: 'テレビ番組風テロップ素材集 Vol.1', short: 'TV風テロップ Vol.1', price: 1980 },
    'variety-vol1': { name: 'バラエティ特化 ツッコミ・リアクションテロップ集', short: 'バラエティ Vol.1', price: 1980 },
    'news-vol1': { name: 'ニュース・報道テロップ集', short: 'ニュース Vol.1', price: 1980 },
  };

  const API = { DESIGNS, PACKS, FONTS, googleFontsHref };
  if (typeof module !== 'undefined' && module.exports) module.exports = API;
  global.TelopDesigns = API;
})(typeof window !== 'undefined' ? window : globalThis);
